---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# The effect of reduced frequency of diabetes control on cardiovascular risk: a natural experiment during the COVID-19 pandemic

Analytic code for article "The effect of reduced frequency of diabetes control on cardiovascular risk: a natural experiment during the COVID-19 pandemic"

In this study, we leveraged the COVID-19 pandemic and associated disruption to preventive care to assess the effect of reduced frequency of diabetes type 2 monitoring on cardiovascular risk. Most guidelines for treatment of type 2 diabetes recommend monitoring two to four times a year; in the Netherlands approximately two thirds of diabetes patients are monitored at least four times per year by their general practitioner. We hypothesized that during the pandemic, some patients skipped these periodic check-ups or were unable to access their GP due to public closures. 

The objective of this study is to determine whether the disruption to primary care caused by the COVID-19 pandemic led to higher incidence of cardiovascular disease among patients with type 2 diabetes. In a broader context, we aimed to assess the efficiency of cardiovascular risk monitoring among diabetic patients and investigate the consequence of reducing its frequency. 

Manusript currently submitted for publication.
